name: Scheduler

on:
  push:
    branches:
      - master
  schedule:
    - cron: '25 23 * * SUN'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Cache pip
        uses: actions/cache@v1
        with:
          # このパスはUbuntu固有
          path: ~/.cache/pip
          # 対応する要件ファイルにキャッシュヒットがあるかどうかを確認する
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Set up mecab
        run: |
          sudo apt-get update
          sudo apt-get install -y mecab
          sudo apt-get install -y mecab-utils
          sudo apt-get install -y libmecab-dev
      - name: Pip install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: deploy bot
        run: python marcov.py
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          MECABRC: /etc/mecabrc
          TW_418_ID: ${{ secrets.TW_418_ID }}